name: Chroot Teste
on: [push]
jobs:
  check-debian:
    runs-on: ubuntu-latest
    steps:
      - name: Debian
        uses: Sirherobrine23/Debian_ISO@main
        with:
          DIST: 'Debian Teste'
          DIST_BASE: "debian"
          REPO_URL: "http://ftp.debian.org/debian"
          SPACE: 'false'
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}

      - name: Upload To Releases
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Debian
          tag_name: ${{ github.run_id }}
          files: "*.iso"

      - name: Delete Old Releases
        uses: dev-drprasad/delete-older-releases@v0.1.0
        with:
          keep_latest: 2
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  check-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Ubuntu
        uses: Sirherobrine23/Debian_ISO@main
        with:
          DIST: 'Ubuntu Teste'
          DIST_BASE: "ubuntu"
          REPO_URL: "http://archive.ubuntu.com/ubuntu"
          SPACE: 'false'
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}

      - name: Upload To Releases
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ubuntu
          tag_name: ${{ github.run_id }}
          files: "*.iso"

      - name: Delete Old Releases
        uses: dev-drprasad/delete-older-releases@v0.1.0
        with:
          keep_latest: 2
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}